version: '3.5'
name: lynshare-compose
services:
  database:
    image: postgres:15.3-alpine3.18
    container_name: database
    expose:
      - "5432"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      restart: unless-stopped