import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Navbar } from "../components/layouts/navbar";
import AuthProvider from "../context/auth-provider";
import { ThemeProvider } from "../context/theme-provider";
import "./globals.css";
import "../components/plate-ui/code-block-element.css"
const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<AuthProvider>
							<Navbar /> {children}
					</AuthProvider>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
